### ISSUE TITLE
Allow the use of `calc()` and CSS variables combination value in positioning properties such as `left`

### ISSUE THREAD

**Issue by alistair3149** [octfx/mediawiki-extensions-TemplateStylesExtender#22]
Currently, the following styles will return `Invalid or unsupported value for property`. It would be great to allow the use of both `calc()` and CSS variables as the value.
```CSS
.item {
	left: calc( var( --var1 ) / var( --var2 ) * 100% );
	right: calc( ( var( --var1 ) - var( --var2 ) ) / var( --var3 ) * 100% );
}
```
