### ISSUE TITLE
Add support for relative colors

### ISSUE THREAD

**Issue by AyIong** [octfx/mediawiki-extensions-TemplateStylesExtender#27]
`background-color: hsl(from <color> h s l / a)`
- MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors
- Can I Use: https://caniuse.com/css-relative-colors

**Comment by octfx** [comment]
I've added some initial support for this.  
If possible, could you check/test the changes from the develop branch and report any possible issues?

**Comment by Xeverything11** [comment]
<img width="878" alt="Image" src="https://github.com/user-attachments/assets/be1923d3-3f40-45b1-b3cf-dbfd7666ae72" />

Just tested at a wiki, relative colors are not working.

**Comment by octfx** [comment]
I guess this has to be due to the use of `a` for the alpha value.

Looking at the MDN docs I am guessing that `alpha` has to be a number or percentage? 
https://developer.mozilla.org/en-US/docs/Web/CSS/alpha-value

Meaning `hsl(from green 211 s l / 1)` should work

**Comment by AyIong** [comment]
Tested on local wiki, it works, but doesn't support alpha channel and calculations
```css
background-color: hsl(from red 180 s calc(l - 25));
```

But this will wokr
```css
background-color: hsl(from red 180 s 75);
```

**Comment by AyIong** [comment]
Just tested `calc` support
If there is no vars into the calc, it works fine
```css
.test {
	background-color: hsl(from var(--color-primary) h calc(s - 25) l / 0.66);
}

.test:hover {
	background-color: hsl(from var(--color-primary) h calc(s - 25) calc(l + 10) / 0.66);
}
```

But if you add var in calc, there will be an error
```css
.test {
	background-color: hsl(from var(--color-primary) h calc(s - 25) l / 0.66);
}

.test:hover {
	background-color: hsl(from var(--color-primary) h calc(s - 25) calc(l + var(--adjust-hover)) / 0.66);
}
```

Anyway, that's great, you're the best ❤
